from datetime import datetime, timezone

PERMANENT_SUBSCRIPTION_DAYS = 36500
PERMANENT_END_DATE = datetime(2100, 1, 1, tzinfo=timezone.utc)

TELEGRAM_MESSAGE_LIMIT = 4096

TRAFFIC_SYNC_INTERVAL = 900
NOTIFICATION_INTERVAL = 1800
STALE_PAYMENT_THRESHOLD = 3600
WORKER_ERROR_SLEEP_INTERVAL = 60

API_CONCURRENCY_LIMIT = 20
API_RETRY_COUNT = 2
API_TIMEOUT = 15
AMNEZIA_PROTOCOL = "amneziawg2"

HUB_CACHE_MAX_SIZE = 10000
HUB_CACHE_TTL = 43200

USER_CONTEXT_CACHE_MAX_SIZE = 2000
USER_CONTEXT_CACHE_TTL = 15.0

DEVICE_DAILY_LIMIT = 25
SELF_HEALING_MAX_PER_CYCLE = 50